package:
  name: aglcheck
  version: "0.2.0b"

source:
  git-url: https://github.com/gjlbeckers-uu/aglcheck.git
  git-rev: v0.2.0b

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pyyaml
    - numpy
    - matplotlib

test:
  requires:
    - yaml
  imports:
    - aglcheck

about:
  license: BSD
  license_file: LICENSE